default: &default
  adapter: postgresql
  username: postgres
  password: postgres
  host: localhost
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dfaqui_development

test:
  <<: *default
  database: dfaqui_test

production:
  <<: *default
  database: dfaqui_production
  username: dfaqui_admin
  password: <%= ENV['DFAQUI_ADMIN_DATABASE_PASSWORD'] %>
